### ISSUE TITLE
项目运行起来，但是点赞，评论都会出这个登录的问题，请问是要注意哪里配置？THX!

### ISSUE THREAD

**Issue by rickhjl** [seasonstar/egg-24time#6]
服务器报错：
2017-08-06 01:06:40,872 ERROR 26435 [-/127.0.0.1/-/2ms POST /v1/posts/2016/like] nodejs.Error: ERR_LOGIN_FAILED
    at LoginServiceError (/data/egg-24time/node_modules/egg-weapp-sdk/lib/auth/login-service-error.js:5:5)
    at LoginService.<anonymous> (/data/egg-24time/node_modules/egg-weapp-sdk/lib/auth/login-service.js:54:23)
    at throw (native)
    at onRejected (/data/egg-24time/node_modules/co/index.js:81:24)
    at process._tickCallback (internal/process/next_tick.js:109:7)
type: 'ERR_INVALID_SESSION'

**Comment by rickhjl** [comment]
原来是之前保存在本地存储中的信息没有删除，所以一直没有触发到服务器的登录功能。手动删除下就成功触发了。大赞楼主的代码！
